# Generated by Django 2.2 on 2020-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('weather_condition', models.CharField(max_length=30)),
                ('weather_icon', models.CharField(max_length=10)),
                ('weather_id', models.IntegerField()),
            ],
        ),
    ]
