# Generated by Django 2.2 on 2020-06-04 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openweather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherbase',
            name='date_today',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weatherbase',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weatherbase',
            name='wind_speed',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
