# Generated by Django 2.2 on 2020-06-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openweather', '0002_auto_20200604_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherbase',
            name='date_today',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
